project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "Business Decisions with Machine Learning Journal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals"
            file: content/01_journal/01_ml_fund.qmd
          - text: "02 Supervised ML - Regression"
            file: content/01_journal/ml.qmd
          - text: "03 Automated Machine Learning Questions"
            file: content/01_journal/auto_ml_1.qmd
          - text: "04/05 Automated Machine Learning (II) and Performance measures"
            file: content/01_journal/auto_ml_perf.qmd
          - text: "06 Explaining Models with LIME"
            file: content/01_journal/lime.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto